In [2]:
import torch

In [3]:
# Создайте случайный FloatTensor размера 3x4x5
sample = torch.rand(3, 4, 5).type(torch.float)
sample

tensor([[[0.5276, 0.5003, 0.7618, 0.8391, 0.9005],
         [0.7970, 0.0787, 0.6695, 0.5604, 0.5721],
         [0.1060, 0.3242, 0.9994, 0.3757, 0.5902],
         [0.8106, 0.4112, 0.5477, 0.4190, 0.9549]],

        [[0.6032, 0.0889, 0.3479, 0.4410, 0.2172],
         [0.5232, 0.7103, 0.8925, 0.6157, 0.8852],
         [0.0473, 0.6883, 0.4830, 0.7135, 0.7798],
         [0.3618, 0.0878, 0.1313, 0.9187, 0.9897]],

        [[0.4736, 0.3353, 0.4518, 0.8424, 0.7494],
         [0.7773, 0.3118, 0.7458, 0.8072, 0.2988],
         [0.5852, 0.0754, 0.0085, 0.9382, 0.9985],
         [0.7680, 0.1211, 0.1997, 0.3171, 0.4753]]])

In [4]:
# Выведите его форму (shape)
sample.shape, sample.size()

(torch.Size([3, 4, 5]), torch.Size([3, 4, 5]))

In [5]:
# Приведите его к форме 6 X 10
sample_reshape = sample.reshape((6, 10))
sample_reshape, sample_reshape.size()

(tensor([[0.5276, 0.5003, 0.7618, 0.8391, 0.9005, 0.7970, 0.0787, 0.6695, 0.5604,
          0.5721],
         [0.1060, 0.3242, 0.9994, 0.3757, 0.5902, 0.8106, 0.4112, 0.5477, 0.4190,
          0.9549],
         [0.6032, 0.0889, 0.3479, 0.4410, 0.2172, 0.5232, 0.7103, 0.8925, 0.6157,
          0.8852],
         [0.0473, 0.6883, 0.4830, 0.7135, 0.7798, 0.3618, 0.0878, 0.1313, 0.9187,
          0.9897],
         [0.4736, 0.3353, 0.4518, 0.8424, 0.7494, 0.7773, 0.3118, 0.7458, 0.8072,
          0.2988],
         [0.5852, 0.0754, 0.0085, 0.9382, 0.9985, 0.7680, 0.1211, 0.1997, 0.3171,
          0.4753]]),
 torch.Size([6, 10]))

In [6]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
sample_reshape = sample_reshape.cuda()
res = sample_reshape.reshape((-1, 5)) * torch.tensor([1, 4, 2, 2, 1]).type(torch.int).cuda()
res

tensor([[0.5276, 2.0011, 1.5236, 1.6782, 0.9005],
        [0.7970, 0.3149, 1.3390, 1.1208, 0.5721],
        [0.1060, 1.2968, 1.9988, 0.7515, 0.5902],
        [0.8106, 1.6448, 1.0955, 0.8380, 0.9549],
        [0.6032, 0.3554, 0.6958, 0.8820, 0.2172],
        [0.5232, 2.8413, 1.7850, 1.2313, 0.8852],
        [0.0473, 2.7532, 0.9659, 1.4269, 0.7798],
        [0.3618, 0.3512, 0.2626, 1.8375, 0.9897],
        [0.4736, 1.3413, 0.9036, 1.6847, 0.7494],
        [0.7773, 1.2472, 1.4916, 1.6143, 0.2988],
        [0.5852, 0.3014, 0.0170, 1.8764, 0.9985],
        [0.7680, 0.4843, 0.3993, 0.6342, 0.4753]], device='cuda:0')

In [7]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
res_2 = sample_reshape @ sample_reshape.T
res_2, res_2.size()

(tensor([[4.3549, 3.6525, 3.1152, 3.5023, 3.9100, 3.2442],
         [3.6525, 3.8182, 3.0426, 3.1704, 3.1596, 2.4052],
         [3.1152, 3.0426, 3.4719, 2.5522, 3.0621, 2.2752],
         [3.5023, 3.1704, 2.5522, 3.8057, 3.1005, 2.6080],
         [3.9100, 3.1596, 3.0621, 3.1005, 3.8104, 3.0264],
         [3.2442, 2.4052, 2.2752, 2.6080, 3.0264, 3.1962]], device='cuda:0'),
 torch.Size([6, 6]))

In [8]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y = x ** 3 + z - 75 * t

print(f'y([1, 0.5, 2]): {y.item()}\nderivative: {(3 * x ** 2 + 1 - 75).item()}')

y([1, 0.5, 2]): -148.5
derivative: -71.0


In [9]:
# Создайте единичный тензор размера 5x6
ones = torch.ones((5, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# Переведите его в формат numpy
ones.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [ ]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 